2) Corrected cv2.rectangle coordinates
Corrected coordinates, so that they fit to the image (eg when a green dot is detected, the green rectangle is around the dot and not a few cms above)

ERROR: Assertion out of range